<?php
$text = strtr($text, array("\r\n" => '<br />', "\r" => '<br />', "\n" => '<br />', 
':Д' => '<img src="img/smiles/D.gif" />',
':д' => '<img src="img/smiles/D.gif" />', 
':томат' => '<img src="img/tomato.gif"/>', 
'=D' => '<img src="img/smiles/D.gif" />', 
':-D' => '<img src="img/smiles/D.gif" />', 
':D' => '<img src="img/smiles/D.gif" />', 
':царь' => '<img src="img/smiles/korol3.gif" />', 
':король' => '<img src="img/smiles/korol3.gif" />', 
':аномалия1' => '<img src="img/smiles/anomaliya.gif" />', 
':ган' => '<img src="img/smiles/gun.gif" />', 
';)' => '<img src="img/smiles/04_wink.gif" />', 
';-)' => '<img src="img/smiles/04_wink.gif" />', 
'упыри' => 'молодцы', 
'выродки' => 'молодцы', 
'уроды' => 'молодцы', 
'чмыри' => 'молодцы', 
'суки' => 'молодцы', 
'пидары' => 'молодцы', 
'упырь' => 'молодец', 
'выродок' => 'молодец', 
'урод' => 'молодец', 
'чмо' => 'молодец', 
'сука' => 'молодец', 
'пидар' => 'молодец', 
':гитара' => '<img src="img/smiles/gitara.gif" />',
':-)' => '<img src="img/smiles/smile.gif" />',
 '=)' => '<img src="img/smiles/smile2.gif" />',
':)' => '<img src="img/smiles/smile.gif" />',
':-(' => '<img src="img/smiles/sad.gif" />', 
':(' => '<img src="img/smiles/sad.gif" />',  
':P' => '<img src="img/smiles/09_bebe.gif" />', 
':-P' => '<img src="img/smiles/09_bebe.gif" />', 
':-Р' => '<img src="img/smiles/09_bebe.gif" />', 
':Р' => '<img src="img/smiles/09_bebe.gif" />', 
':ржу' => '<img src="img/smiles/rzhu.gif" />', 
':фан' => '<img src="img/smiles/fan.gif" />', 
':умора' => '<img src="img/smiles/umora.gif" />', 
':раста' => '<img src="img/smiles/rasta.gif" />', 
':фэйспалм' => '<img src="img/smiles/facepalm.gif" />', 
':facepalm' => '<img src="img/smiles/facepalm.gif" />', 
':доволен1' => '<img src="img/smiles/dovolen.gif" />', 
':доволен2' => '<img src="img/smiles/dovolen2.gif" />', 
':пират' => '<img src="img/smiles/pirat.gif" />', 
':олень' => '<img src="img/smiles/olen.gif" />', 


':собака' => '<img src="img/monsters/3.png" width="30" height="30" border="0"/>', 


':зло' => '<img src="img/smiles/zlo.gif" />', 
":хмм" =>'<img src="img/smiles/xmm.gif" />', 
":пишу" =>'<img src="img/smiles/mail3.gif" />', 
":хаха" => '<img src="img/smiles/xaxa.gif" />', 
':жопа' => '<img src="img/smiles/zhopa.gif" />', 
':гг' => '<img src="img/smiles/gg.gif" />', 
':летает' => '<img src="img/smiles/letaet.gif" />', 
":ого" => '<img src="img/smiles/vau.gif" />', 
":тихо" => '<img src="img/smiles/tiho.gif" />', 
":смерть" => '<img src="img/smiles/smert.gif" />', 
":поиск" => '<img src="img/smiles/poisk.gif" />', 
":накрыло" => '<img src="img/smiles/pizdec.gif" />', 
":оу" => '<img src="img/smiles/oy.gif" />', 
":упс" => '<img src="img/smiles/oops.gif" />', 
":ням" => '<img src="img/smiles/nyam.gif" />', 
":ноно" => '<img src="img/smiles/nono.gif" />', 
":нет" => '<img src="img/smiles/no.gif" />', 
":ниндзя" => '<img src="img/smiles/ninja.gif" />', 
":незнаю" => '<img src="img/smiles/neznaju.gif" />', 
":неа" => '<img src="img/smiles/nea.gif" />', 
":муз" => '<img src="img/smiles/music.gif" />', 
":мистер" => '<img src="img/smiles/mister.gif" />', 
":ламер" => '<img src="img/smiles/lamer.gif" />', 
":кыш" => '<img src="img/smiles/kulak.gif" />', 
":крут" => '<img src="img/smiles/krut.gif" />', 
":кул" => '<img src="img/smiles/klass.gif" />', 
":класс" => '<img src="img/smiles/klass.gif" />', 
":супер" => '<img src="img/smiles/klass.gif" />', 
":пока" => '<img src="img/smiles/hello.gif" />', 
":фак" => '<img src="img/smiles/fuck.gif" />', 
":флуд" => '<img src="img/smiles/flood.gif" />', 
":фингал" => '<img src="img/smiles/fingal.gif" />', 
":холодно" => '<img src="img/smiles/cold.gif" />', 
":бомба" => '<img src="img/smiles/bomba.gif" />', 
":блин" => '<img src="img/smiles/blin.gif" />', 
":бан1" => '<img src="img/smiles/ban.gif" />', 
":идиот" => '<img src="img/smiles/crazy.gif" />', 
":[" => '<img src="img/smiles/[.gif" />', 
":качок" => '<img src="img/smiles/bb.gif" />', 
":атлет" => '<img src="img/smiles/atlet.gif" />', 
":ааа" => '<img src="img/smiles/aaa.gif" />', 
":испуг" => '<img src="img/smiles/scare.gif" />', 
":аааа" => '<img src="img/smiles/scare.gif" />', 
":плак" => '<img src="img/smiles/cray.gif" />',
':плак ' => '<img src="img/smiles/cray.gif" />',
":глаза" => '<img src="img/smiles/8.gif" />', 
":8" => '<img src="img/smiles/8.gif" />',  
':тост' => '<img src="img/smiles/tost.gif" />', 
':*' => '<img src="img/smiles/25_kiss.gif" />',

':баян' => '<img src="img/smiles/bajan.gif" />',
':чмак' => '<img src="img/smiles/chmak.gif" />',
':чмок2' => '<img src="img/smiles/chmok2.gif" />',
':влюбви1' => '<img src="img/smiles/inlove1.gif" />',
':влюбви2' => '<img src="img/smiles/inlove2.gif" />',
':влюбви3' => '<img src="img/smiles/inlove3.gif" />',
':письмо1' => '<img src="img/smiles/mail.gif" />',
':письмо2' => '<img src="img/smiles/mail2.gif" />',
':нравится' => '<img src="img/smiles/nravitsya.gif" />',
':сердце' => '<img src="img/smiles/serdce.gif" />',
':стеснит1' => '<img src="img/smiles/stesnit.gif" />',
':стеснит2' => '<img src="img/smiles/stesnit2.gif" />',
':воздп' => '<img src="img/smiles/vozdp.gif" />',
':укостра' => '<img src="img/smiles/smil0.gif" />',
':бан2' => '<img src="img/smiles/ban2.gif" />',
':артефакт' => '<img src="img/smiles/smile_artefact.gif" />',
':монолит' => '<img src="img/smiles/image.jpg" />',
':аномалия2' => '<img src="img/smiles/9950.gif" />',
':полтергейст' => '<img src="img/smiles/520500.gif" />',
':пиво' => '<img src="img/smiles/drink.gif" />',
':контролёр' => '<img src="img/smiles/smile_control.gif" />',
':контролер' => '<img src="img/smiles/smile_control.gif" />',
':кровосос' => '<img src="img/smiles/smile_krovosos.gif" />',
':псевдогигант' => '<img src="img/smiles/smile_pseudogigant.gif" />',
':снорк' => '<img src="img/smiles/smile_snork.gif" />',
':стена' => '<img src="img/smiles/wall.gif" />',
':ура2' => '<img src="img/smiles/yahoo.gif" />'
));
?>